# coding=utf-8
#
# This list is based on [1], so it should be used and distributed under the
# terms of the Creative Commons Attribution-ShareAlike License.
# [1] http://en.wikipedia.org/wiki/List_of_adjectival_and_demonymic_forms_of_place_names
#

"""Country name to demonym table."""

__author__ = "leandro@tia.mat.br (Leandro Pereira)"

COUNTRY_DEMONYMS = {
    u'ERITREA': u'Eritrean',
    u'PORTUGAL': u'Portuguese',
    u'KOSOVO': u'Kosovan',
    u'INDIA': u'Indian',
    u'MONTENEGRO': u'Montenegrin',
    u'NEW CALEDONIA': u'New Caledonian',
    u'UZBEKISTAN': u'Uzbek',
    u'TOGO': u'Togolese',
    u'ARUBA': u'Aruban',
    u'MICRONESIA': u'Micronesian',
    u'IRAN': u'Irani',
    u'MALTA': u'Maltese',
    u'KIRIBATI': u'Kiribatian',
    u'BARBADOS': u'Barbadian',
    u'BENIN': u'Beninese',
    u'IRAQ': u'Iraqi',
    u'CHAD': u'Chadian',
    u'SAINT HELENA': u'Saint Helenian',
    u'TAJIKISTAN': u'Tajikistani',
    u'COSTA RICA': u'Costa Rican',
    u'ETHIOPIA': u'Ethiopian',
    u'SWEDEN': u'Swede',
    u'RWANDA': u'Rwandan',
    u'OMAN': u'Omani',
    u'SURINAME': u'Surinamer',
    u'ZAMBIA': u'Zambian',
    u'ANGUILLA': u'Anguillan',
    u'NORWAY': u'Norwegian',
    u'QATAR': u'Qatari',
    u'PALAU': u'Palauan',
    u'SUDAN': u'Sudanese',
    u'DENMARK': u'Dane',
    u'NEPAL': u'Nepalese',
    u'AZERBAIJAN': u'Azerbaijani',
    u'PAPUA NEW GUINEA': u'Guinean',
    u'ZIMBABWE': u'Zimbabwean',
    u'GABON': u'Gabonese',
    u'GIBRALTAR': u'Gibraltarian',
    u'SWAZILAND': u'Swazi',
    u'VANUATU': u'Vanuatuan',
    u'YEMEN': u'Yemeni',
    u'VENEZUELA': u'Venezuelan',
    u'ECUADOR': u'Ecuadorean',
    u'BAHAMAS': u'Bahamian',
    u'AUSTRALIA': u'Australian',
    u'ENGLAND': u'Englishman',
    u'KUWAIT': u'Kuwaiti',
    u'TANZANIA': u'Tanzanian',
    u'SCOTLAND': u'Scot',
    u'CENTRAL AFRICAN REPUBLIC': u'Central African',
    u'FRANCE': u'Frenchman',
    u'TRINIDAD AND TOBAGO': u'Trinidadian and Tobagan',
    u'ARMENIA': u'Armenian',
    u'AUSTRIA': u'Austrian',
    u'SRI LANKA': u'Sri Lankan',
    u'CROATIA': u'Croat',
    u'TURKS AND CAICOS ISLANDS': u'Turks and Caicos Islander',
    u'COMOROS': u'Comoran',
    u'TONGA': u'Tongan',
    u'GEORGIA': u'Georgian',
    u'HONDURAS': u'Honduran',
    u'GUINEA-BISSAU': u'Guinean',
    u'LIBYA': u'Libyan',
    u'NORTHERN MARIANAS': u'Northern Mariana Islander',
    u'MAYOTTE': u'Mahorais',
    u'INDONESIA': u'Indonesian',
    u'ANTARCTICA': u'Antarctican',
    u'VIETNAM': u'Vietnamese',
    u'MOZAMBIQUE': u'Mozambican',
    u'SOUTH SUDAN': u'South Sudanese',
    u'COLOMBIA': u'Colombian',
    u'MARTINIQUE': u'Martinican',
    u'SWITZERLAND': u'Swiss',
    u'CANADA': u'Canadian',
    u'MAURITANIA': u'Mauritanian',
    u'LITHUANIA': u'Lithuanian',
    u'CAMBODIA': u'Cambodian',
    u'EGYPT': u'Egyptian',
    u'CUBA': u'Cuban',
    u'LEBANON': u'Lebanese',
    u'SAINT PIERRE AND MIQUELON': u'Saint-Pierrais',
    u'BOTSWANA': u'Botswanan',
    u'SENEGAL': u'Senegalese',
    u'CONGO': u'Congolese',
    u'ALGERIA': u'Algerian',
    u'MALI': u'Malian',
    u'NEW ZEALAND': u'New Zealander',
    u'VATICAN CITY': u'Vatican',
    u'COOK ISLANDS': u'Cook Islander',
    u'PAKISTAN': u'Pakistani',
    u'REUNIONESE': u'Reunionese',
    u'ANGOLA': u'Angolan',
    u'PRINCIPEAN': u'Principean',
    u'SAINT LUCIA': u'Saint Lucian',
    u'GUYANA': u'Guyanese',
    u'SAINT KITTS AND NEVIS': u'Kittsian',
    u'MALAYSIA': u'Malaysian',
    u'SAINT VINCENT AND THE GRENADINES': u'Saint Vincentian',
    u'GHANA': u'Ghanaian',
    u'IRELAND': u'Irishman',
    u'SYRIA': u'Syrian',
    u'NIGERIA': u'Nigerian',
    u'NORTH KOREA': u'North Korean',
    u'KYRGYZSTAN': u'Kirgizia',
    u'BANGLADESH': u'Bangladeshi',
    u'ESTONIA': u'Estonian',
    u'SLOVENIA': u'Slovenian',
    u'ICELAND': u'Icelander',
    u'SEYCHELLES': u'Seychellois',
    u'RUSSIA': u'Russian',
    u'LESOTHO': u'Mosotho',
    u'TUNISIA': u'Tunisian',
    u'BRITISH VIRGIN ISLANDS': u'British Virgin Islander',
    u'BOSNIA AND HERZEGOVINA': u'Bosnian',
    u'MONACO': u'Monacan',
    u'WALLIS AND FUTUNA': u'Wallis and Futuna Islander',
    u'UKRAINE': u'Ukrainian',
    u'BRUNEI': u'Bruneian',
    u'ISRAEL': u'Israeli',
    u'IVORY COAST': u'Ivoirian',
    u'KHALISTAN': u'Sikhistan',
    u'MEXICO': u'Mexican',
    u'TUVALU': u'Tuvaluan',
    u'SERBIA': u'Serbian',
    u'CAPE VERDE': u'Cape Verdean',
    u'UNITED KINGDOM': u'Briton',
    u'MOROCCO': u'Moroccan',
    u'NETHERLANDS': u'Holland',
    u'UGANDA': u'Ugandan',
    u'GRENADA': u'Grenadian',
    u'THAILAND': u'Thai',
    u'MONTSERRAT': u'Montserratian',
    u'BOLIVIA': u'Bolivian',
    u'SIERRA LEONE': u'Sierra Leonian',
    u'BRAZIL': u'Brazilian',
    u'MADAGASCAR': u'Madagascan',
    u'ALBANIA': u'Albanian',
    u'CZECH REPUBLIC': u'Czech',
    u'SOUTH AFRICA': u'South African',
    u'BRITAIN': u'Northern Ireland',
    u'SINGAPORE': u'Singaporean',
    u'GERMANY': u'German',
    u'PUERTO RICO': u'Puerto Rican',
    u'NIGER': u'Nigerien',
    u'NICARAGUA': u'Nicaraguan',
    u'MALAWI': u'Malawian',
    u'NIUE': u'Niuean',
    u'EAST TIMOR': u'East Timorese',
    u'SAUDI ARABIA': u'Saudi',
    u'ITALY': u'Italian',
    u'PERU': u'Peruvian',
    u'PHILIPPINES': u'Filipino',
    u'KENYA': u'Kenyan',
    u'BERMUDA': u'Bermudian',
    u'FRENCH GUIANA': u'Guianese',
    u'SOMALIA': u'Somali',
    u'PALESTINE': u'Palestinian',
    u'ARGENTINA': u'Argentinian',
    u'CYPRUS': u'Cypriot',
    u'BAHRAIN': u'Bahraini',
    u'FALKLAND ISLANDS': u'Falkland Islander',
    u'MALDIVES': u'Maldivian',
    u'WESTERN SAHARA': u'Sahrawi',
    u'CAYMAN ISLANDS': u'Caymanian',
    u'MARSHALL ISLANDS': u'Marshallese',
    u'MONGOLIA': u'Mongolian',
    u'LATVIA': u'Latvian',
    u'SLOVAKIA': u'Slovak',
    u'LAOS': u'Lao',
    u'BELGIUM': u'Belgian',
    u'GAMBIA': u'Gambian',
    u'BURKINA FASO': u'Burkinabe',
    u'US VIRGIN ISLANDS': u'US Virgin Islander',
    u'LIBERIA': u'Liberian',
    u'AFGHANISTAN': u'Afghan',
    u'KAZAKHSTAN': u'Kazakh',
    u'GUAM': u'Guamanian',
    u'AMERICAN SAMOA': u'American Samoan',
    u'MOLDOVA': u'Moldavia',
    u'MAURITIUS': u'Mauritian',
    u'LIECHTENSTEIN': u'Liechtensteiner',
    u'MYANMAR': u'Burma',
    u'NAMIBIA': u'Namibian',
    u'GREECE': u'Hellas',
    u'WALES': u'Welshman',
    u'NAURU': u'Nauruan',
    u'BELIZE': u'Belizean',
    u'FIJI': u'Fijian',
    u'TAIWAN': u'Republic of China',
    u'ROMANIA': u'Romanian',
    u'GREENLAND': u'Greenlander',
    u'TIBET': u'Tibetan',
    u'EL SALVADOR': u'Salvadoran',
    u'POLAND': u'Pole',
    u'UNITED STATES OF AMERICA': u'American',
    u'BRITTANY': u'Breton',
    u'LUXEMBOURG': u'Luxembourger',
    u'NORFOLK ISLAND': u'Norfolk Islander',
    u'ANTIGUA AND BARBUDA': u'Antiguan',
    u'CHRISTMAS ISLAND': u'Christmas Islander',
    u'HUNGARY': u'Hungarian',
    u'FAEROE ISLANDS': u'Faeroese',
    u'EUROPEAN UNION': u'European',
    u'SPAIN': u'Spaniard',
    u'CATALONIA': u'Catalan',
    u'JAMAICA': u'Jamaican',
    u'SOLOMON ISLANDS': u'Solomon Islander',
    u'UNITED ARAB EMIRATES': u'Emirati',
    u'FINLAND': u'Finn',
    u'COCOS ISLANDER': u'Cocos',
    u'PITCAIRN ISLANDS': u'Pitcairner',
    u'ANDORRA': u'Andorran',
    u'DJIBOUTI': u'Djiboutian',
    u'BELARUS': u'Byelorussia',
    u'JORDAN': u'Jordanian',
    u'MACEDONIA': u'Macedonian',
    u'JAPAN': u'Japanese',
    u'PARAGUAY': u'Paraguayan',
    u'DOMINICAN REPUBLIC': u'Dominican',
    u'HAITI': u'Haitian',
    u'DOMINICA': u'Dominican',
    u'TURKEY': u'Turk',
    u'SAMOA': u'Samoan',
    u'TURKMENISTAN': u'Turkmenia',
    u'BHUTAN': u'Bhutanese',
    u'URUGUAY': u'Uruguayan',
    u'GUINEA': u'Guinean',
    u'PANAMA': u'Panamanian',
    u'EQUATORIAL GUINEA': u'Equatorial Guinean',
    u'SAN MARINO': u'Sammarinese',
    u'FRENCH POLYNESIA': u'Polynesian',
    u'TOKELAU': u'Tokelauan',
    u'GUATEMALA': u'Guatemalan',
    u'CHILE': u'Chilean',
    u'BURUNDI': u'Burundian',
    u'CHINA': u'Chinese',
    u'SOUTH KOREA': u'South Korean',
    u'GUADELOUPE': u'Guadeloupean',
    u'CAMEROON': u'Cameroonian',
    u'BULGARIA': u'Bulgarian',
    u'BOUVET ISLAND': u'Bouvetan',
    u'BRITISH INDIAN OCEAN TERRITORY': u'British Indian',
    u'BRUNEI DARUSSALAM': u'Bruneian',
    u'COCOS (KEELING) ISLANDS': u'Cocos Islander',
    u'CONGO, THE DEMOCRATIC REPUBLIC OF THE': u'Congolese',
    u'CÔTE D\'IVOIRE': u'Ivorian',
    u'FALKLAND ISLANDS (MALVINAS)': u'Falkland Islander',
    u'FAROE ISLANDS': u'Faroese',
    u'HEARD ISLAND AND MCDONALD ISLANDS': u'Heard Islander',
    u'HOLY SEE (VATICAN CITY STATE)': u'Vatican Resident',
    u'HONG KONG': u'Hongkongese',
    u'IRAN, ISLAMIC REPUBLIC OF': u'Iranian',
    u'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF': u'North Korean',
    u'KOREA, REPUBLIC OF': u'Korean',
    u'LAO PEOPLE\'S DEMOCRATIC REPUBLIC': u'Laotian',
    u'LIBYAN ARAB JAMAHIRIYA': u'Libyan',
    u'MACAO': u'Macanese',
    u'MICRONESIA, FEDERATED STATES OF': u'Micronesian',
    u'MOLDOVA, REPUBLIC OF': u'Moldovan',
    u'NORTHERN MARIANA ISLANDS': u'Northern Marianan',
    u'PALESTINIAN TERRITORY, OCCUPIED': u'Palestinian',
    u'PITCAIRN': u'Pitcairn Islander',
    u'RUSSIAN FEDERATION': u'Russian',
    u'RÉUNION': u'Réunionese',
    u'SAO TOME AND PRINCIPE': u'São Toméan',
    u'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS': u'South Sandwich Islander',
    u'SVALBARD AND JAN MAYEN': u'Svalbardian',
    u'SYRIAN ARAB REPUBLIC': u'Syrian',
    u'TAIWAN, PROVINCE OF CHINA': u'Taiwanese',
    u'TANZANIA, UNITED REPUBLIC OF': u'Tanzanian',
    u'TIMOR-LESTE': u'Timorese',
    u'UNITED STATES': u'American',
    u'UNITED STATES MINOR OUTLYING ISLANDS': u'American',
    u'VIET NAM': u'Vietnamese',
    u'VIRGIN ISLANDS, BRITISH': u'Virgin Islander',
    u'VIRGIN ISLANDS, U.S.': u'Virgin Islander',
    u'[CITIZEN OF THE WORLD]': u'Earthling',
    u'[UNLISTED COUNTRY]': u'Unknownian',
}
